# Generated by Django 2.2.27 on 2024-05-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0039_task_orthophoto_bands'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the model', max_length=255, verbose_name='Name')),
                ('file_name', models.CharField(help_text='Name of the model file', max_length=255, verbose_name='File name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date', verbose_name='Created at')),
                ('owner', models.ForeignKey(help_text='The user who uploaded a model', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
