# Generated by Django 2.2.27 on 2024-05-26 11:43

import app.models.new_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_modelfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfiles',
            name='file',
            field=models.FileField(blank=True, help_text='File being saved', null=True, upload_to=app.models.new_upload.user_directory_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='modelfiles',
            name='file_name',
            field=models.CharField(help_text='Name of the file', max_length=255, verbose_name='File name'),
        ),
    ]
