# Generated by Django 2.2.27 on 2024-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20240526_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfiles',
            name='file',
        ),
        migrations.AddField(
            model_name='modelfiles',
            name='file_url',
            field=models.URLField(blank=True, help_text='Cloudinary url of the file', max_length=255, verbose_name='File url'),
        ),
    ]
