# Generated by Django 2.2.27 on 2024-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20240527_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfiles',
            name='page_url',
            field=models.URLField(blank=True, help_text='Page url for the model', max_length=255, verbose_name='Page url'),
        ),
    ]
